### ISSUE TITLE
Is there a best practice to add an API for adding new short urls?

### ISSUE THREAD

**Issue by josefglatz** [sudhaus7/typo3-shortlink#2]
I don't know if this is a feature request or just a question. I think such would be great to easily add new urls via an token authentication or something like that? What do you think @foppelfb ?

**Comment by foppelfb** [comment]
This could easily be done with a Middleware. The Authentication part would have to be added, and with the ShortlinkService::encode method the url could be encoded, given by a payload. 

Do you have a nice example for a Token Based authentication?

**Comment by josefglatz** [comment]
I have never written an authentication 😣🤪. I was just thinking about a simple authentication like the ext:t3monitoring does without private/public keys.

**Comment by foppelfb** [comment]
I'll check it out, it could be a worthwhile feature :)

**Comment by josefglatz** [comment]
Awesome! 



Diese Nachricht wurde von meinem Smartphone versandt

**Comment by foppelfb** [comment]
Check out the new Version
